gem "github-pages", group: :jekyll_plugins
remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Devin Upreti"
title_separator          : "-"
name                     : "Devin Upreti"
description              : "Portfolio"
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200

# Site Author
author:
  name             : "Devin Upreti"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Data Scientist / Software Developer"
  location         : "NY"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:dupreti@syr.com
    - label: "LinkedIn"
      icon: "fas fa-linkedin-in"
      url: "https://www.linkedin.com/in/devinupreti/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/devinupreti"
      

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
